name: don
description: |
  Data Object Notation, an alternative to JSON, YAML and TOML,
  is a sophisticated language to express data that supports expressions,
  variables, types, schema validations and content assist.
# version: 1.0.0
# homepage: https://www.example.com
# author: Issac <tejainece@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  string_scanner:

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
